<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="2" failed="1" skipped="7">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-03T13:08:55 IST" name="Default suite" finished-at="2023-12-03T13:10:04 IST" duration-ms="68653">
    <groups>
    </groups>
    <test started-at="2023-12-03T13:08:55 IST" name="Default test" finished-at="2023-12-03T13:10:04 IST" duration-ms="68653">
      <class name="tests.Myinfo">
        <test-method signature="login()[pri:0, instance:tests.Myinfo@78e4deb0]" started-at="2023-12-03T13:08:55 IST" name="login" finished-at="2023-12-03T13:09:31 IST" duration-ms="35840" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="home()[pri:0, instance:tests.Myinfo@78e4deb0]" started-at="2023-12-03T13:09:31 IST" name="home" finished-at="2023-12-03T13:09:34 IST" depends-on-methods="tests.Myinfo.login" duration-ms="2954" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- home -->
        <test-method signature="personal()[pri:0, instance:tests.Myinfo@78e4deb0]" started-at="2023-12-03T13:09:34 IST" name="personal" finished-at="2023-12-03T13:10:04 IST" depends-on-methods="tests.Myinfo.login, tests.Myinfo.home" duration-ms="29737" status="FAIL">
          <exception class="org.openqa.selenium.InvalidSelectorException">
            <message>
              <![CDATA[invalid selector: Unable to locate an element with the xpath expression //input[@class='oxd-input oxd-input--active'])[9] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//input[@class='oxd-input oxd-input--active'])[9]' is not a valid XPath expression.
  (Session info: chrome=119.0.6045.200)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [414db5cb63588d7ad6c52ce908d94cf5, findElement {using=xpath, value=//input[@class='oxd-input oxd-input--active'])[9]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 119.0.6045.200, chrome: {chromedriverVersion: 119.0.6045.105 (38c72552c5e..., userDataDir: C:\Users\mohit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55800}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:55800/devtoo..., se:cdpVersion: 119.0.6045.200, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 414db5cb63588d7ad6c52ce908d94cf5]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression //input[@class='oxd-input oxd-input--active'])[9] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//input[@class='oxd-input oxd-input--active'])[9]' is not a valid XPath expression.
  (Session info: chrome=119.0.6045.200)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [414db5cb63588d7ad6c52ce908d94cf5, findElement {using=xpath, value=//input[@class='oxd-input oxd-input--active'])[9]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 119.0.6045.200, chrome: {chromedriverVersion: 119.0.6045.105 (38c72552c5e..., userDataDir: C:\Users\mohit\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55800}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:55800/devtoo..., se:cdpVersion: 119.0.6045.200, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 414db5cb63588d7ad6c52ce908d94cf5
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy14.sendKeys(Unknown Source)
at pageelements.Personaldetails.personalinfo(Personaldetails.java:145)
at tests.Myinfo.personal(Myinfo.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.InvalidSelectorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- personal -->
        <test-method signature="contact()[pri:0, instance:tests.Myinfo@78e4deb0]" started-at="2023-12-03T13:10:04 IST" name="contact" finished-at="2023-12-03T13:10:04 IST" depends-on-methods="tests.Myinfo.personal, tests.Myinfo.login, tests.Myinfo.home" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contact -->
        <test-method signature="emergency()[pri:0, instance:tests.Myinfo@78e4deb0]" started-at="2023-12-03T13:10:04 IST" name="emergency" finished-at="2023-12-03T13:10:04 IST" depends-on-methods="tests.Myinfo.contact, tests.Myinfo.personal, tests.Myinfo.login, tests.Myinfo.home" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emergency -->
        <test-method signature="dependents()[pri:0, instance:tests.Myinfo@78e4deb0]" started-at="2023-12-03T13:10:04 IST" name="dependents" finished-at="2023-12-03T13:10:04 IST" depends-on-methods="tests.Myinfo.contact, tests.Myinfo.emergency, tests.Myinfo.personal, tests.Myinfo.login, tests.Myinfo.home" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method tests.Myinfo.dependents() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method tests.Myinfo.dependents() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dependents -->
        <test-method signature="quit()[pri:0, instance:tests.Myinfo@78e4deb0]" started-at="2023-12-03T13:10:04 IST" name="quit" finished-at="2023-12-03T13:10:04 IST" depends-on-methods="tests.Myinfo.qualification, tests.Myinfo.immigration, tests.Myinfo.contact, tests.Myinfo.emergency, tests.Myinfo.personal, tests.Myinfo.dependents, tests.Myinfo.membership, tests.Myinfo.login, tests.Myinfo.home" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method tests.Myinfo.quit() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.qualification() on instance tests.Myinfo@78e4deb0
tests.Myinfo.immigration() on instance tests.Myinfo@78e4deb0
tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.dependents() on instance tests.Myinfo@78e4deb0
tests.Myinfo.membership() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method tests.Myinfo.quit() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.qualification() on instance tests.Myinfo@78e4deb0
tests.Myinfo.immigration() on instance tests.Myinfo@78e4deb0
tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.dependents() on instance tests.Myinfo@78e4deb0
tests.Myinfo.membership() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method signature="qualification()[pri:0, instance:tests.Myinfo@78e4deb0]" started-at="2023-12-03T13:10:04 IST" name="qualification" finished-at="2023-12-03T13:10:04 IST" depends-on-methods="tests.Myinfo.immigration, tests.Myinfo.contact, tests.Myinfo.emergency, tests.Myinfo.personal, tests.Myinfo.dependents, tests.Myinfo.login, tests.Myinfo.home" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method tests.Myinfo.qualification() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.immigration() on instance tests.Myinfo@78e4deb0
tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.dependents() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method tests.Myinfo.qualification() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.immigration() on instance tests.Myinfo@78e4deb0
tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.dependents() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- qualification -->
        <test-method signature="membership()[pri:0, instance:tests.Myinfo@78e4deb0]" started-at="2023-12-03T13:10:04 IST" name="membership" finished-at="2023-12-03T13:10:04 IST" depends-on-methods="tests.Myinfo.qualification, tests.Myinfo.immigration, tests.Myinfo.contact, tests.Myinfo.emergency, tests.Myinfo.personal, tests.Myinfo.dependents, tests.Myinfo.login, tests.Myinfo.home" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method tests.Myinfo.membership() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.qualification() on instance tests.Myinfo@78e4deb0
tests.Myinfo.immigration() on instance tests.Myinfo@78e4deb0
tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.dependents() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method tests.Myinfo.membership() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.qualification() on instance tests.Myinfo@78e4deb0
tests.Myinfo.immigration() on instance tests.Myinfo@78e4deb0
tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.dependents() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- membership -->
        <test-method signature="immigration()[pri:0, instance:tests.Myinfo@78e4deb0]" started-at="2023-12-03T13:10:04 IST" name="immigration" finished-at="2023-12-03T13:10:04 IST" depends-on-methods="tests.Myinfo.contact, tests.Myinfo.emergency, tests.Myinfo.personal, tests.Myinfo.dependents, tests.Myinfo.login, tests.Myinfo.home" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method tests.Myinfo.immigration() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.dependents() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method tests.Myinfo.immigration() on instance tests.Myinfo@78e4deb0 depends on not successfully finished methods 
[tests.Myinfo.contact() on instance tests.Myinfo@78e4deb0
tests.Myinfo.emergency() on instance tests.Myinfo@78e4deb0
tests.Myinfo.personal() on instance tests.Myinfo@78e4deb0
tests.Myinfo.dependents() on instance tests.Myinfo@78e4deb0
tests.Myinfo.login() on instance tests.Myinfo@78e4deb0
tests.Myinfo.home() on instance tests.Myinfo@78e4deb0]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- immigration -->
      </class> <!-- tests.Myinfo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
